// ── add_concept_descriptions.cypher ──────────────────────────────────────
// Run this in AuraDB Browser after final_restructure_knowledge_graph.cypher
// Adds description and scope fields to all Concept nodes.
// Safe to re-run: SET is idempotent.
//
// Purpose: Provides richer grounding data for the faithfulness classifier
// in rag_explainer.py. Without descriptions, the classifier has only node
// names and tree structure — not enough to distinguish legitimate consulting
// elaboration from out-of-scope claims.
//
// Source authority per framework:
//   Expanded Profit Formula  → Victor Cheng (caseinterview.com PDF)
//   Economic Feasibility     → Original design doc taxonomy
//   Four-Pronged Strategy    → Original design doc taxonomy
//   Formulaic Breakdown      → Original design doc taxonomy
//   Customized Issue Trees   → Original design doc taxonomy
//   MA Fit Framework         → Victor Cheng (caseinterview.com PDF)
//   Capacity Change          → Victor Cheng (caseinterview.com PDF)
//
// Change log: 2026-03-31 — added to support faithfulness classifier grounding.
// ══════════════════════════════════════════════════════════════════════════


// ── Expanded Profit Formula ───────────────────────────────────────────────

MATCH (c:Concept {name: "Revenue", framework: "Expanded Profit Formula"})
SET c.description = "Total income generated by the business. Calculated as Price per Unit multiplied by Units Sold. Branch node — groups the two revenue-side drivers.";

MATCH (c:Concept {name: "Costs", framework: "Expanded Profit Formula"})
SET c.description = "Total expenditure incurred by the business. Comprises Fixed Cost and Variable Cost. Branch node — groups all cost-side drivers.";

MATCH (c:Concept {name: "Variable Cost", framework: "Expanded Profit Formula"})
SET c.description = "Costs that scale directly with production volume. Comprises Cost per Unit and the shared driver Units Sold. Branch node — groups variable cost components.";

MATCH (c:Concept {name: "Price per Unit", framework: "Expanded Profit Formula"})
SET c.description = "The selling price charged per unit of output. Analytical scope: market pricing rates, buyer negotiating power, pricing strategy relative to competitors. Sits under Revenue alongside Units Sold.";

MATCH (c:Concept {name: "Units Sold", framework: "Expanded Profit Formula"})
SET c.description = "The volume of units sold or extracted. Analytical scope: demand forecasting, extraction capacity, market demand estimation. Sits under Revenue and also drives Variable Cost via ALSO_DRIVES.";

MATCH (c:Concept {name: "Fixed Cost", framework: "Expanded Profit Formula"})
SET c.description = "Overhead costs that do not vary with production volume. Analytical scope: equipment purchases, setup costs, administrative overhead, lease or site costs. Sits under Costs alongside Variable Cost.";

MATCH (c:Concept {name: "Cost per Unit", framework: "Expanded Profit Formula"})
SET c.description = "The variable production cost incurred per unit. Analytical scope: extraction costs, processing costs, transportation costs per unit to end market. Sits under Variable Cost.";


// ── Economic Feasibility ──────────────────────────────────────────────────

MATCH (c:Concept {name: "Market Potential", framework: "Economic Feasibility"})
SET c.description = "The revenue opportunity available in the target market. Branch node grouping Market Size, Market Share, and Profit per Unit.";

MATCH (c:Concept {name: "Implementation", framework: "Economic Feasibility"})
SET c.description = "The operational challenges of executing market entry. Branch node grouping Production, Distribution, and Marketing Challenges.";

MATCH (c:Concept {name: "Market Size", framework: "Economic Feasibility"})
SET c.description = "The total addressable market in units or revenue. Analytical scope: market volume estimates, growth rates, demand trends.";

MATCH (c:Concept {name: "Market Share", framework: "Economic Feasibility"})
SET c.description = "The proportion of the market the client can realistically capture. Analytical scope: competitive positioning, customer acquisition, penetration assumptions.";

MATCH (c:Concept {name: "Profit per Unit", framework: "Economic Feasibility"})
SET c.description = "The margin earned per unit sold in the target market. Analytical scope: pricing relative to cost, margin benchmarks, revenue per transaction.";

MATCH (c:Concept {name: "Production Challenges", framework: "Economic Feasibility"})
SET c.description = "Operational barriers to producing the product or service at required scale. Analytical scope: manufacturing capacity, supply chain, quality standards, regulatory requirements.";

MATCH (c:Concept {name: "Distribution Challenges", framework: "Economic Feasibility"})
SET c.description = "Barriers to getting the product from production to end customers. Analytical scope: logistics, channel partnerships, last-mile delivery, infrastructure.";

MATCH (c:Concept {name: "Marketing Challenges", framework: "Economic Feasibility"})
SET c.description = "Barriers to reaching and converting target customers. Analytical scope: brand awareness, customer education, promotional strategy, competitive differentiation.";


// ── Four-Pronged Strategy ─────────────────────────────────────────────────

MATCH (c:Concept {name: "Cost-based Pricing", framework: "Four-Pronged Strategy"})
SET c.description = "Setting price based on cost of production plus a target margin. Analytical scope: cost structure analysis, margin targets, break-even pricing.";

MATCH (c:Concept {name: "Competitor-based Pricing", framework: "Four-Pronged Strategy"})
SET c.description = "Setting price relative to competitor prices. Analytical scope: competitive benchmarking, price positioning, market rate analysis.";

MATCH (c:Concept {name: "Value-to-Customer Pricing", framework: "Four-Pronged Strategy"})
SET c.description = "Setting price based on the value delivered to the customer. Analytical scope: willingness to pay, customer perceived value, value proposition differentiation.";

MATCH (c:Concept {name: "Price-Elasticity Pricing", framework: "Four-Pronged Strategy"})
SET c.description = "Setting price based on how demand responds to price changes. Analytical scope: demand sensitivity, volume-price trade-offs, elasticity estimation.";


// ── Formulaic Breakdown ───────────────────────────────────────────────────

MATCH (c:Concept {name: "Demand-side", framework: "Formulaic Breakdown"})
SET c.description = "The demand-driven estimation approach. Branch node grouping Demand-side Estimation and Population Segmentation.";

MATCH (c:Concept {name: "Population Segmentation", framework: "Formulaic Breakdown"})
SET c.description = "Breaking the target population into segments to estimate demand. Branch node grouping Age, Gender, and Income segmentation.";

MATCH (c:Concept {name: "Supply-side Constraints", framework: "Formulaic Breakdown"})
SET c.description = "Estimating a quantity by starting from supply capacity. Analytical scope: production limits, throughput, capacity utilisation.";

MATCH (c:Concept {name: "Demand-side Estimation", framework: "Formulaic Breakdown"})
SET c.description = "Estimating total demand from first principles using proxies. Analytical scope: reference models, analogous markets, proxy-based extrapolation.";

MATCH (c:Concept {name: "Population Segmentation Age", framework: "Formulaic Breakdown"})
SET c.description = "Segmenting the population by age group to estimate demand. Analytical scope: age distribution, age-specific consumption rates.";

MATCH (c:Concept {name: "Population Segmentation Gender", framework: "Formulaic Breakdown"})
SET c.description = "Segmenting the population by gender to estimate demand. Analytical scope: gender-specific consumption patterns and rates.";

MATCH (c:Concept {name: "Population Segmentation Income", framework: "Formulaic Breakdown"})
SET c.description = "Segmenting the population by income level to estimate demand. Analytical scope: income brackets, affordability, purchasing power distribution.";


// ── Customized Issue Trees ────────────────────────────────────────────────

MATCH (c:Concept {name: "Internal Factors", framework: "Customized Issue Trees"})
SET c.description = "Factors within the organisation's control. Analytical scope: operations, capabilities, cost structure, people, processes, technology.";

MATCH (c:Concept {name: "External Factors", framework: "Customized Issue Trees"})
SET c.description = "Factors outside the organisation's control. Analytical scope: market conditions, regulation, competition, macroeconomic environment, customer behaviour.";

MATCH (c:Concept {name: "Mathematical Parameter Division", framework: "Customized Issue Trees"})
SET c.description = "Decomposing a metric into its mathematical components. Analytical scope: formula breakdowns such as Time = Distance / Speed, Revenue = Price × Volume.";


// ── MA Fit Framework ──────────────────────────────────────────────────────

MATCH (c:Concept {name: "Customer", framework: "MA Fit Framework"})
SET c.description = "The customer base of the company being evaluated. Analytical scope: customer segments, concentration, overlap with acquirer's customers, switching behaviour.";

MATCH (c:Concept {name: "Company", framework: "MA Fit Framework"})
SET c.description = "The internal capabilities and structure of the target company. Analytical scope: distribution channels, cost structure, intangibles, financial situation, organisational structure.";

MATCH (c:Concept {name: "Product", framework: "MA Fit Framework"})
SET c.description = "The products or services offered by the target company. Analytical scope: product nature, differentiation, substitutes, lifecycle stage, complementarity with acquirer.";

MATCH (c:Concept {name: "Competition", framework: "MA Fit Framework"})
SET c.description = "The competitive landscape the combined entity would face. Analytical scope: competitor concentration, barriers to entry, industry lifecycle, regulatory environment.";


// ── Capacity Change Framework ─────────────────────────────────────────────

MATCH (c:Concept {name: "Demand", framework: "Capacity Change Framework"})
SET c.description = "The sustainability and trajectory of market demand. Analytical scope: overall market growth, firm-specific demand growth, demand segmentation by customer type or region.";

MATCH (c:Concept {name: "Supply", framework: "Capacity Change Framework"})
SET c.description = "The current and future supply landscape. Analytical scope: industry supply volume, effect of new supply on price, supply segmentation by market.";

MATCH (c:Concept {name: "Cost of Expansion", framework: "Capacity Change Framework"})
SET c.description = "The financial and opportunity cost of adding capacity. Analytical scope: real capital costs, payback period, break-even analysis, alternatives such as outsourcing or leasing.";


// ══════════════════════════════════════════════════════════════════════════
// VERIFY — run separately
// MATCH (c:Concept) WHERE c.description IS NOT NULL
// RETURN c.name, c.framework, c.description
// ORDER BY c.framework, c.name;
// ══════════════════════════════════════════════════════════════════════════
